version: '7.1'

x-superset-image: &superset-image ferrettivinicius/superset
x-superset-volumes: &superset-volumes
  - ./superset/docker:/app/docker
  - ./superset/superset_home:/app/superset_home

networks:
  net:
    driver: bridge

services:

  minio:
      image: minio/minio:latest
      hostname: minio
      container_name: minio
      environment:
        - MINIO_ROOT_USER=ifood 
        - MINIO_ROOT_PASSWORD=ifood@123
      volumes:
        - ./minio:/data
      networks:
        - net
      ports:
        - 9000:9000
        - 9001:9001
      command: server /data --console-address ":9001"

  postgres:
    image: postgres:14
    container_name: postgres
    restart: unless-stopped
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - net
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=ifood
      - POSTGRES_PASSWORD=ifood@123
      - POSTGRES_DB=db_ifood
      - PGDATA=/var/lib/postgresql/data

  airflow:
    image: ferrettivinicius/airflow-aula-fia:latest
    hostname: airflow
    container_name: airflow
    depends_on:
      - postgres
    volumes:
        - ./airflow/dags:/usr/local/airflow/dags
        - ./airflow/jars:/usr/local/airflow/jars
        - ./airflow/config:/usr/local/airflow/config
        - ./airflow/plugins:/usr/local/airflow/plugins
    networks:
        - net
    ports:
        - 8080:8080

  jupyter:
    image: pentos/pyspark-notebook
    hostname: jupyter
    container_name: jupyter
    ports:
      - 8888:8888
    networks:
      - net
    volumes:
      - ./jupyter/notebooks:/home/jovyan/notebooks
      - ./jupyter/jars:/home/jovyan/jars

  trino:
    hostname: trino
    image: 'trinodb/trino:351'
    ports:
      - '8086:8080'
    volumes:
      - ./trino:/usr/lib/trino/etc:ro
    networks:
      - net
    depends_on:
      - hive-metastore
      - minio

  hive-metastore:
    hostname: hive-metastore
    image: 'bitsondatadev/hive-metastore:latest'
    ports:
      - '9083:9083' # Metastore Thrift
    volumes:
      - ./hive-metastore/conf/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
    environment:
      METASTORE_DB_HOSTNAME: mariadb
    depends_on:
      - mariadb
    networks:
      - net

  mariadb:
    hostname: mariadb
    image: mariadb:10.5.8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db
    networks:
      - net
    
  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    volumes:
      - ./redis:/data
    networks:
      - net

  superset:
    image: *superset-image
    container_name: superset_app
    restart: unless-stopped
    ports:
      - 8088:8088
    depends_on: 
      - superset-init
      - redis
    networks:
      - net
    volumes: *superset-volumes
    user: "root"
    env_file: ./superset/docker/.env-non-dev
    command: ["/app/docker/docker-bootstrap.sh", "app-gunicorn"]

  superset-init:
    image: *superset-image
    container_name: superset_init
    depends_on: 
      - postgres
    healthcheck:
      disable: true
    networks:
      - net
    volumes: *superset-volumes
    user: "root"
    env_file: ./superset/docker/.env-non-dev
    command: ["/app/docker/docker-init.sh"]